version: '3'

services:
    flask:
       build:
         context: .    
         dockerfile: Dockerfile 
       ports: 
         - 5001:5001
       networks:
         - elastic

networks:
  elastic:
    driver: bridge
         

